version: '3.8'

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "${PUID:-1000}:${PGID:-1000}"
    # Remove network_mode: "host" for Windows
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Oslo}
      - JELLYFIN_PublishedServerUrl=http://192.168.1.176:8096
    volumes:
      - ./config:/config
      - ./cache:/cache
      - H:\Video:/media:ro
    ports:
      # Explicitly map ports
      - "8096:8096"
      - "8920:8920"
      - "1900:1900/udp"
      - "7359:7359/udp"
    restart: unless-stopped